### PR TITLE
day21 morning task accomplished

### PR DESCRIPTION
**Pull request by Kellsonphilips**

### CODE REVIEW

**Review by alicalimli — APPROVED** [review]

**Comment by Kellsonphilips** [comment]
Ali, are you a maintainer now?

Pardon me if I didn't know lol

**Comment by alicalimli** [comment]
No, i was just testing the reviewing stuff sorry bout that 😅

**Comment by avie-dev** [comment]
@Kellsonphilips lol.. yeah, I opened the review to everyone.. let's talk about this later hahah

**Review by avie-dev — APPROVED** [review]
Nice consistency. I sent an invitation to the org. Please accept

**Comment by Kellsonphilips** [comment]
Oh, let me check it out

**Comment by Kellsonphilips** [comment]
I just did, thanks Avie. Do we have to co-review a PR before it's merged?

**Comment by Kellsonphilips** [comment]
@alicalimli no worries haha 😂

**Pull request merged**
