### PR TITLE
Week-2 - Asakatsu - Arya Learning Nihongo

### PR DESCRIPTION
**Pull request by AryaCodesAI**
Yaaay! I won the silver league and got promoted to the Gold league. I am so happy, two weeks of consistency is paying off.

### CODE REVIEW

**Review by Kellsonphilips — APPROVED** [review]
Massive progress Arya 💪

**Review by avie-dev — APPROVED** [review]
Nice Arya Chaaan!

**Comment by AryaCodesAI** [comment]
> Nice Arya Chaaan!

Arigatou Avie chan!

**Comment by AryaCodesAI** [comment]
> Massive progress Arya 💪

Thank you, Philips!

**Pull request merged**
