### PR TITLE
Tracking daily tasks

### PR DESCRIPTION
**Pull request by watacodes**
Thanks a lot for checking!! Hope you're enjoying the weekend! :D

### CODE REVIEW

**Review by Kellsonphilips — APPROVED** [review]
codewars or leetcode?

**Comment by watacodes** [comment]
@Kellsonphilips  It's codewars! 😸

**Comment by Kellsonphilips** [comment]
Thanks for that answer @watacodes. Sorry to ask, is there any specific feature to take out in codewars that is lacking in leetcode?

**Comment by watacodes** [comment]
@Kellsonphilips Not at all! To be honest, I've never tried Leetcode yet so I'm not really sure about the difference between the two platforms, but I've heard that Leetcode questions in general are more challenging than codewars questions.

**Comment by Kellsonphilips** [comment]
Thanks for the response.

**Pull request merged**
