### PR TITLE
day11&12 morning task completed

### PR DESCRIPTION
**Pull request by Kellsonphilips**

### CODE REVIEW

**Comment by Kellsonphilips** [comment]
Ask chaanal to fix his folder inside report dir and make a new PR so I can update my main

**Comment by avie-dev** [comment]
> Ask chaanal to fix his folder inside report dir and make a new PR so I can update my main
chaanal's folder is inside report, and you are trying to erase the files inside it in this PR.

**Comment by Kellsonphilips** [comment]
My mistake, it was appearing on my PR and I was thinking removing it won't affect your side.

**Comment by Kellsonphilips** [comment]
If Chaanal can make a new PR then I will update my develop to have his files back

**Pull request closed without merging**
