### PR TITLE
self check routine

### PR DESCRIPTION
**Pull request by Kellsonphilips**

### CODE REVIEW

**Review by avie-dev — APPROVED** [review]
I'm curious about how many days you are working on this already, the consistency is so great, wow!

**Comment by Kellsonphilips** [comment]
My streak broke at 244 days but I started a new streak, and at 25 days now.
I traveled back to Nigeria last month and the two days journey broke my streak of 244 days.

**Comment by avie-dev** [comment]
let's call that pause and continue the streak. So you are near to 1 year!

**Comment by Kellsonphilips** [comment]
Yes, in maybe 2 months It will be a year streak but missing 2 days. That hurts, right?

**Pull request merged**
