### PR TITLE
day28 task accomplished

### PR DESCRIPTION
**Pull request by Kellsonphilips**

### CODE REVIEW

**Review by Kellsonphilips — COMMENTED** [review]
2 more days

**Comment by alisamadiii** [comment]
let's gooooooo 🥳🥳🥳

**Review by avie-dev — APPROVED** [review]
Ooooh! Last 2days Philips! I can't believe how time flies and how consistent you are

**Comment by Kellsonphilips** [comment]
Me too, I can't believe I stayed this consistent haha. 
I am happy with my improvements and I want to do more, really.

**Pull request merged**
