### PR TITLE
Week 3-Arya Learning Nihongo- Asakatsu Project

### PR DESCRIPTION
**Pull request by AryaCodesAI**
About to complete three weeks, I am so excited!

### CODE REVIEW

**Review by Kellsonphilips — APPROVED** [review]
I think @avie-dev  forgot the PRs. Let me take care of it.

**Comment by Kellsonphilips** [comment]
Great progress @AryaCodesAI

**Comment by AryaCodesAI** [comment]
> I think @avie-dev forgot the PRs. Let me take care of it.

Thank you so much, Philips! I appreciate it.

**Comment by AryaCodesAI** [comment]
> Great progress @AryaCodesAI

Yes! Thanks for the support!

**Pull request merged**
