### PR TITLE
Tracking daily tasks

### PR DESCRIPTION
**Pull request by watacodes**
Thanks a lot for checking! You too have a great day :)

### CODE REVIEW

**Review by Kellsonphilips — APPROVED** [review]
Sorry brother, I was travelling and couldn't do anything on my laptop.

**Comment by watacodes** [comment]
@Kellsonphilips Welcome back, Philips! How was your trip? Hope it was a good one. :)

**Comment by Kellsonphilips** [comment]
Everything was fine, I was traveling to Nigeria from India and we had a stop. I haven't reached my country yet.

**Comment by watacodes** [comment]
@Kellsonphilips Ohh, it seems pretty hectic for you! Have a safe trip! 😁

**Comment by Kellsonphilips** [comment]
Thank you so much brother, we will be checking even though airport wifi is not safe. 
How was your week like?

**Comment by watacodes** [comment]
@Kellsonphilips No worries mate, you can't risk your data and info if it seems unsafe! My week was quite hectic, but it's finally a day off so I'm happy. :D

**Comment by Kellsonphilips** [comment]
Too many stop overs for my flight. I will reach my home tomorrow.

**Pull request merged**
